#ifndef GREENBOARD_H_
#define GREENBOARD_H_

#include <gpio>

#include "Board.h"


// Slave select lines
#define RADAR_N_SLAVE_SELECT_PORT GPIO_PORT_P1
#define RADAR_E_SLAVE_SELECT_PORT GPIO_PORT_P2
#define RADAR_S_SLAVE_SELECT_PORT
#define RADAR_W_SLAVE_SELECT_PORT

#define RADAR_N_SLAVE_SELECT_PIN GPIO_PIN0
#define RADAR_E_SLAVE_SELECT_PIN GPIO_PIN0
#define RADAR_S_SLAVE_SELECT_PIN
#define RADAR_W_SLAVE_SELECT_PIN

// MISO Lines
#define RADAR_N_MISO_PORT GPIO_PORT_P1
#define RADAR_E_MISO_PORT GPIO_PORT_P2
#define RADAR_S_MISO_PORT
#define RADAR_W_MISO_PORT

#define RADAR_N_MISO_PIN GPIO_PIN1
#define RADAR_E_MISO_PIN GPIO_PIN1
#define RADAR_S_MISO_PIN
#define RADAR_W_MISO_PIN

// MOSI Lines
#define RADAR_N_MOSI_PORT GPIO_PORT_P1
#define RADAR_E_MOSI_PORT GPIO_PORT_P1
#define RADAR_S_MOSI_PORT
#define RADAR_W_MOSI_PORT

#define RADAR_N_MOSI_PIN GPIO_PIN3
#define RADAR_E_MOSI_PIN GPIO_PIN3
#define RADAR_S_MOSI_PIN
#define RADAR_W_MOSI_PIN

// CLK Lines
#define RADAR_N_SLAVE_SELECT_PORT
#define RADAR_E_SLAVE_SELECT_PORT
#define RADAR_S_SLAVE_SELECT_PORT
#define RADAR_W_SLAVE_SELECT_PORT

#define RADAR_N_SLAVE_SELECT_PIN
#define RADAR_E_SLAVE_SELECT_PIN
#define RADAR_S_SLAVE_SELECT_PIN
#define RADAR_W_SLAVE_SELECT_PIN

// SDA Lines
#define LIDAR_N_SDA_PORT GPIO_PORT_P1
#define LIDAR_E_SDA_PORT GPIO_PORT_P6
#define LIDAR_S_SDA_PORT
#define LIDAR_W_SDA_PORT

#define LIDAR_N_SDA_PIN GPIO_PIN6
#define LIDAR_E_SDA_PIN GPIO_PIN5
#define LIDAR_S_SDA_PIN
#define LIDAR_W_SDA_PIN

// SCL Lines
#define LIDAR_N_SCL_PORT GPIO_PORT_P1
#define LIDAR_E_SCL_PORT GPIO_PORT_P6
#define LIDAR_S_SCL_PORT
#define LIDAR_W_SCL_PORT

#define LIDAR_N_SCL_PIN GPIO_PIN7
#define LIDAR_E_SCL_PIN GPIO_PIN4
#define LIDAR_S_SCL_PIN
#define LIDAR_W_SCL_PIN


#define RED_N_PORT GPIO_PORT_P7
#define RED_E_PORT GPIO_PORT_P7
#define RED_S_PORT
#define RED_W_PORT

#define RED_N_PIN GPIO_PIN4
#define RED_E_PIN GPIO_PIN5
#define RED_S_PIN
#define RED_W_PIN


#define YELLOW_N_PORT GPIO_PORT_P7
#define YELLOW_E_PORT GPIO_PORT_P7
#define YELLOW_S_PORT
#define YELLOW_W_PORT

#define YELLOW_N_PIN GPIO_PIN6
#define YELLOW_E_PIN GPIO_PIN7
#define YELLOW_S_PIN
#define YELLOW_W_PIN






#endif // GREENBOARD_H_
